name: feedcanary
type: php
docroot: public
php_version: "8.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
database:
    type: mariadb
    version: "10.4"
composer_version: "2"
nodejs_version: "18"