name: feedcanary
type: php
docroot: public
php_version: "8.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
database:
    type: postgres
    version: "16"
composer_version: "2"
nodejs_version: "20"
web_extra_exposed_ports:
  - name: vite
    container_port: 3000
    http_port: 3001
    https_port: 3000
